// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// IPF_cpp
NumericMatrix IPF_cpp(NumericMatrix matriz, NumericVector vector_columna, NumericVector vector_fila, double precision);
RcppExport SEXP _ecolRxC_IPF_cpp(SEXP matrizSEXP, SEXP vector_columnaSEXP, SEXP vector_filaSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matriz(matrizSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector_columna(vector_columnaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector_fila(vector_filaSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(IPF_cpp(matriz, vector_columna, vector_fila, precision));
    return rcpp_result_gen;
END_RCPP
}
// IPF2_cpp
NumericMatrix IPF2_cpp(NumericMatrix matriz, NumericVector vector_columna, NumericVector vector_fila, double precision);
RcppExport SEXP _ecolRxC_IPF2_cpp(SEXP matrizSEXP, SEXP vector_columnaSEXP, SEXP vector_filaSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matriz(matrizSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector_columna(vector_columnaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector_fila(vector_filaSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(IPF2_cpp(matriz, vector_columna, vector_fila, precision));
    return rcpp_result_gen;
END_RCPP
}
// reweighting_pjk_cpp
List reweighting_pjk_cpp(NumericVector pjk_flat, IntegerVector dims, int ref1, int ref2, std::string scale, NumericMatrix x, NumericMatrix y, double tol);
RcppExport SEXP _ecolRxC_reweighting_pjk_cpp(SEXP pjk_flatSEXP, SEXP dimsSEXP, SEXP ref1SEXP, SEXP ref2SEXP, SEXP scaleSEXP, SEXP xSEXP, SEXP ySEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pjk_flat(pjk_flatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type ref1(ref1SEXP);
    Rcpp::traits::input_parameter< int >::type ref2(ref2SEXP);
    Rcpp::traits::input_parameter< std::string >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(reweighting_pjk_cpp(pjk_flat, dims, ref1, ref2, scale, x, y, tol));
    return rcpp_result_gen;
END_RCPP
}
// reweighting_pjk_Yule_cpp
List reweighting_pjk_Yule_cpp(NumericVector pjk_flat, IntegerVector dims, int ref1, int ref2, std::string scale, NumericMatrix x, NumericMatrix y, double tol);
RcppExport SEXP _ecolRxC_reweighting_pjk_Yule_cpp(SEXP pjk_flatSEXP, SEXP dimsSEXP, SEXP ref1SEXP, SEXP ref2SEXP, SEXP scaleSEXP, SEXP xSEXP, SEXP ySEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pjk_flat(pjk_flatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< int >::type ref1(ref1SEXP);
    Rcpp::traits::input_parameter< int >::type ref2(ref2SEXP);
    Rcpp::traits::input_parameter< std::string >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(reweighting_pjk_Yule_cpp(pjk_flat, dims, ref1, ref2, scale, x, y, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ecolRxC_IPF_cpp", (DL_FUNC) &_ecolRxC_IPF_cpp, 4},
    {"_ecolRxC_IPF2_cpp", (DL_FUNC) &_ecolRxC_IPF2_cpp, 4},
    {"_ecolRxC_reweighting_pjk_cpp", (DL_FUNC) &_ecolRxC_reweighting_pjk_cpp, 8},
    {"_ecolRxC_reweighting_pjk_Yule_cpp", (DL_FUNC) &_ecolRxC_reweighting_pjk_Yule_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecolRxC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
