# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IPF_cpp <- function(matriz, vector_columna, vector_fila, precision = 1e-6) {
    .Call(`_ecolRxC_IPF_cpp`, matriz, vector_columna, vector_fila, precision)
}

IPF2_cpp <- function(matriz, vector_columna, vector_fila, precision = 0.01) {
    .Call(`_ecolRxC_IPF2_cpp`, matriz, vector_columna, vector_fila, precision)
}

reweighting_pjk_cpp <- function(pjk_flat, dims, ref1, ref2, scale, x, y, tol = 1e-6) {
    .Call(`_ecolRxC_reweighting_pjk_cpp`, pjk_flat, dims, ref1, ref2, scale, x, y, tol)
}

reweighting_pjk_Yule_cpp <- function(pjk_flat, dims, ref1, ref2, scale, x, y, tol = 1e-6) {
    .Call(`_ecolRxC_reweighting_pjk_Yule_cpp`, pjk_flat, dims, ref1, ref2, scale, x, y, tol)
}

